# Render.com configuration
services:
  - type: web
    name: life-dashboards
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p instance uploads static/uploads
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: life-dashboards-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000