"""add daily_scores table

Revision ID: 811674234097
Revises: ce5c28de92ab
Create Date: 2025-10-29 14:39:22.198236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811674234097'
down_revision = 'ce5c28de92ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=10), nullable=False),
    sa.Column('task_text', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_type', 'position', name='uq_user_task_position')
    )
    with op.batch_alter_table('user_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tasks_user_id'))

    op.drop_table('user_tasks')
    # ### end Alembic commands ###
